name: aoc
description: Advent of Code monorepo 
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  melos: ^6.2.0
